### ISSUE TITLE
[BUG] Fatal error during build on linux mint 20.1

### ISSUE THREAD

**Issue by avma** [ncmpcpp/ncmpcpp#448]
**Describe the bug**
Running ./autogen.sh and  ./configure ends with the following error messages:

❯       grep "fatal" config.log
g++: fatal error: no input files 
g++: fatal error: no input files
gcc: fatal error: no input files
gcc: fatal error: no input files
conftest.c:11:10: fatal error: ac_nonexistent.h: No such file or directory
conftest.c:11:10: fatal error: ac_nonexistent.h: No such file or directory
conftest.cpp:23:10: fatal error: ac_nonexistent.h: No such file or directory
conftest.cpp:23:10: fatal error: ac_nonexistent.h: No such file or directory
conftest.cpp:84:10: fatal error: readline.h: No such file or directory
conftest.cpp:51:10: fatal error: readline.h: No such file or directory
conftest.cpp:86:10: fatal error: history.h: No such file or directory
conftest.cpp:53:10: fatal error: history.h: No such file or directory
❯       grep "gcc: error" config.log
gcc: error: unrecognized command line option '-V'
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?`

**To Reproduce**
1. run ./autogen.sh and  ./configure
2.  see config.log

**Expected behavior**
Complete w/o errors

**Desktop (please complete the following information):**
 - OS: Linux mint 20.1 cinnamon
 - Terminal: bash
 - Version: 5.0.17

**Additional context**
libreadline-dev and libreadline8 ver 8.04 both present on my machine.
